'use client';

import {useEffect,useMemo,useRef,useState} from 'react';
import {toPng,toJpeg} from 'html-to-image';

const uid=()=>globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random()}`;
const clamp=(n,a,b)=>Math.min(b,Math.max(a,n));
const blends=['normal','multiply','screen','overlay','darken','lighten','color-dodge','color-burn','hard-light','soft-light','difference','exclusion'];
const shapes=['rect','circle','triangle','star','cross','line'];
const fonts=[
  ['Arial, sans-serif','Arial'],['Inter, sans-serif','Inter'],['Oswald, sans-serif','Oswald'],['PT Sans, sans-serif','PT Sans'],['PT Serif, serif','PT Serif'],['Russo One, sans-serif','Russo One'],['Caveat, cursive','Caveat'],['Marck Script, cursive','Marck Script'],['Bad Script, cursive','Bad Script'],['Neucha, cursive','Neucha']
];
const fx0={exposure:0,contrast:100,saturation:100,grayscale:0,blur:0,threshold:0,grain:0,noise:0,scratches:0,halftone:0,xerox:0,fade:0};
const snap=(layers,selectedId)=>JSON.stringify({layers,selectedId});

export default function CollageEditor(){
 const [layers,setLayers]=useState([]),[selectedId,setSelectedId]=useState(null),[ratio,setRatio]=useState('4 / 5'),[bg,setBg]=useState('#f0ede4');
 const [tool,setTool]=useState('select'),[history,setHistory]=useState([]),[future,setFuture]=useState([]),[dragOver,setDragOver]=useState(false),[exporting,setExporting]=useState(false);
 const [repeat,setRepeat]=useState({count:8,spacing:7,angle:0,scale:0,opacity:0,chaos:10});
 const [stamp,setStamp]=useState({type:'text',text:'VOID',size:22,spacing:18,chaos:10,rotationJitter:20,scaleJitter:0,opacityJitter:0,follow:false});
 const canvas=useRef(null),fileRef=useRef(null),gesture=useRef(null),before=useRef(null),brush=useRef(null);
 const selected=useMemo(()=>layers.find(l=>l.id===selectedId)||null,[layers,selectedId]);
 const commit=(next,nextSel=selectedId)=>{setHistory(h=>[...h.slice(-39),snap(layers,selectedId)]);setFuture([]);setLayers(next);setSelectedId(nextSel)};
 const patch=(id,p)=>setLayers(ls=>ls.map(l=>l.id===id?{...l,...p}:l));
 const patchFx=(id,k,v)=>setLayers(ls=>ls.map(l=>l.id===id?{...l,fx:{...fx0,...l.fx,[k]:v}}:l));
 const undo=()=>{if(!history.length)return;const p=JSON.parse(history.at(-1));setFuture(f=>[snap(layers,selectedId),...f].slice(0,40));setHistory(h=>h.slice(0,-1));setLayers(p.layers);setSelectedId(p.selectedId)};
 const redo=()=>{if(!future.length)return;const n=JSON.parse(future[0]);setHistory(h=>[...h,snap(layers,selectedId)].slice(-40));setFuture(f=>f.slice(1));setLayers(n.layers);setSelectedId(n.selectedId)};

 useEffect(()=>{const fn=e=>{const meta=e.metaKey||e.ctrlKey;if(meta&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo()}if(meta&&e.key.toLowerCase()==='d'){e.preventDefault();duplicate()}if((e.key==='Delete'||e.key==='Backspace')&&!['INPUT','TEXTAREA'].includes(document.activeElement?.tagName)){e.preventDefault();remove()}if(e.key==='Escape')setSelectedId(null)};window.addEventListener('keydown',fn);return()=>window.removeEventListener('keydown',fn)});

 async function addFiles(list){const files=[...(list||[])].filter(f=>f.type.startsWith('image/'));const adds=[];for(const f of files){const src=URL.createObjectURL(f);try{const d=await imgSize(src),ar=d.width/d.height;adds.push({id:uid(),type:'image',name:f.name,src,local:true,x:50,y:50,width:ar>=1?38:clamp(38*ar,16,38),height:ar>=1?clamp(38/ar,16,38):38,rotation:0,opacity:1,blend:'normal',hidden:false,locked:false,z:Date.now()+adds.length,fit:'cover',radius:0,fx:{...fx0}})}catch{URL.revokeObjectURL(src)}}if(adds.length)commit([...layers,...adds],adds.at(-1).id)}
 function addText(text='YOUR TEXT'){const l={id:uid(),type:'text',text,x:50,y:50,width:55,height:18,rotation:0,opacity:1,blend:'normal',hidden:false,locked:false,z:Date.now(),color:'#111111',fontFamily:fonts[0][0],fontSize:64,fontWeight:800,tracking:-2,lineHeight:.9,scaleX:1,scaleY:1,outline:0,outlineColor:'#111111',outlineMode:'center'};commit([...layers,l],l.id)}
 function addShape(shape='rect'){const l={id:uid(),type:'shape',shape,x:50,y:50,width:shape==='line'?44:28,height:shape==='line'?6:28,rotation:0,opacity:1,blend:'normal',hidden:false,locked:false,z:Date.now(),fill:'#111111',stroke:'#111111',strokeWidth:0};commit([...layers,l],l.id)}
 function remove(){if(!selected)return;if(selected.local)URL.revokeObjectURL(selected.src);commit(layers.filter(l=>l.id!==selected.id),null)}
 function duplicate(){if(!selected)return;const c={...selected,id:uid(),x:clamp(selected.x+4,0,100),y:clamp(selected.y+4,0,100),z:Date.now()};commit([...layers,c],c.id)}
 function front(){if(!selected)return;const z=Math.max(0,...layers.map(l=>l.z))+1;commit(layers.map(l=>l.id===selected.id?{...l,z}:l),selected.id)}
 function back(){if(!selected)return;const z=Math.min(0,...layers.map(l=>l.z))-1;commit(layers.map(l=>l.id===selected.id?{...l,z}:l),selected.id)}
 function repeatSelected(){if(!selected)return;const copies=[];for(let i=1;i<=repeat.count;i++){const chaos=repeat.chaos/100,rand=()=> (Math.random()-.5)*2*chaos,t=i/repeat.count;copies.push({...selected,id:uid(),x:clamp(selected.x+i*repeat.spacing/2+rand()*14,0,100),y:clamp(selected.y+rand()*14,0,100),rotation:selected.rotation+i*repeat.angle+rand()*32,width:clamp(selected.width*(1+repeat.scale*t/100),2,120),height:clamp(selected.height*(1+repeat.scale*t/100),2,120),opacity:clamp(selected.opacity-repeat.opacity*t/100,.05,1),z:Date.now()+i})}commit([...layers,...copies],selected.id)}
 function variation(){if(!layers.length)return;commit(layers.map((l,i)=>({...l,x:clamp(l.x+(Math.random()-.5)*18,0,100),y:clamp(l.y+(Math.random()-.5)*18,0,100),rotation:l.rotation+(Math.random()-.5)*30,width:clamp(l.width*(.85+Math.random()*.3),3,120),height:clamp(l.height*(.85+Math.random()*.3),3,120),z:Date.now()+i})),selectedId)}
 function clearCanvas(){if(!layers.length)return;if(!confirm('Clear the entire canvas? You can Undo this action.'))return;commit([],null)}
 function makeStamp(x,y,angle=0){const jitter=stamp.chaos/100,rot=angle+(Math.random()-.5)*2*stamp.rotationJitter*jitter,scale=1+(Math.random()-.5)*2*(stamp.scaleJitter/100)*jitter,opacity=clamp(1-Math.random()*(stamp.opacityJitter/100)*jitter,.05,1);if(stamp.type==='text')return {id:uid(),type:'text',text:stamp.text||'STAMP',x,y,width:clamp(stamp.size*scale,2,120),height:10*scale,rotation:rot,opacity,blend:'multiply',hidden:false,locked:false,z:Date.now()+Math.random(),color:'#111',fontFamily:'Oswald, sans-serif',fontSize:58,fontWeight:700,tracking:0,lineHeight:.9,scaleX:1,scaleY:1,outline:0,outlineColor:'#111',outlineMode:'center'};return {id:uid(),type:'shape',shape:stamp.type,x,y,width:clamp(stamp.size/2*scale,2,120),height:clamp(stamp.size/2*scale,2,120),rotation:rot,opacity,blend:'multiply',hidden:false,locked:false,z:Date.now()+Math.random(),fill:'#111',stroke:'#111',strokeWidth:0}}
 function brushDown(e){if(tool!=='stamp')return;e.preventDefault();e.stopPropagation();const r=canvas.current.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*100,y=(e.clientY-r.top)/r.height*100,l=makeStamp(x,y);before.current=snap(layers,selectedId);brush.current={r,lastX:e.clientX,lastY:e.clientY,lastAngle:0};setLayers(ls=>[...ls,l]);setSelectedId(l.id);canvas.current.setPointerCapture?.(e.pointerId)}

 function onLayerDown(e,l){if(tool==='stamp')return;e.stopPropagation();setSelectedId(l.id);if(l.locked)return;const r=canvas.current.getBoundingClientRect();before.current=snap(layers,selectedId);gesture.current={kind:'move',id:l.id,sx:e.clientX,sy:e.clientY,x:l.x,y:l.y,r};e.currentTarget.setPointerCapture?.(e.pointerId)}
 function onHandle(e,l,h){e.stopPropagation();e.preventDefault();const r=canvas.current.getBoundingClientRect(),cx=r.left+r.width*l.x/100,cy=r.top+r.height*l.y/100;before.current=snap(layers,selectedId);gesture.current={kind:h==='rotate'?'rotate':'resize',h,id:l.id,sx:e.clientX,sy:e.clientY,w:l.width,hgt:l.height,r,cx,cy}}
 function move(e){const b=brush.current;if(b&&tool==='stamp'){const dx=e.clientX-b.lastX,dy=e.clientY-b.lastY,dist=Math.hypot(dx,dy);if(dist>=stamp.spacing){const angle=stamp.follow?Math.atan2(dy,dx)*180/Math.PI:0,steps=Math.max(1,Math.floor(dist/stamp.spacing)),adds=[];for(let i=1;i<=steps;i++){const px=b.lastX+dx*i/steps,py=b.lastY+dy*i/steps,x=(px-b.r.left)/b.r.width*100,y=(py-b.r.top)/b.r.height*100;adds.push(makeStamp(x,y,angle))}setLayers(ls=>[...ls,...adds]);b.lastX=e.clientX;b.lastY=e.clientY;b.lastAngle=angle}return}const g=gesture.current;if(!g)return;const l=layers.find(x=>x.id===g.id);if(!l||l.locked)return;if(g.kind==='move'){patch(g.id,{x:clamp(g.x+(e.clientX-g.sx)/g.r.width*100,0,100),y:clamp(g.y+(e.clientY-g.sy)/g.r.height*100,0,100)})}if(g.kind==='resize'){let w=clamp(g.w+(e.clientX-g.sx)/g.r.width*100*(g.h.includes('w')?-2:2),2,120),h=clamp(g.hgt+(e.clientY-g.sy)/g.r.height*100*(g.h.includes('n')?-2:2),2,120);if(e.shiftKey){const ar=g.w/g.hgt;if(Math.abs(e.clientX-g.sx)>Math.abs(e.clientY-g.sy))h=w/ar;else w=h*ar}patch(g.id,{width:w,height:h})}if(g.kind==='rotate'){patch(g.id,{rotation:Math.atan2(e.clientY-g.cy,e.clientX-g.cx)*180/Math.PI+90})}}
 function up(){if(brush.current){if(before.current){setHistory(h=>[...h.slice(-39),before.current]);setFuture([])}brush.current=null;before.current=null;return}if(!gesture.current)return;if(before.current){setHistory(h=>[...h.slice(-39),before.current]);setFuture([])}gesture.current=null;before.current=null}
 function canvasClick(e){if(tool==='select'&&e.target===canvas.current)setSelectedId(null)}
 function reorder(id,dir){const s=[...layers].sort((a,b)=>a.z-b.z),i=s.findIndex(l=>l.id===id),j=clamp(i+dir,0,s.length-1);if(i===j)return;[s[i],s[j]]=[s[j],s[i]];const base=Date.now();commit(s.map((l,k)=>({...l,z:base+k})),id)}
 async function exportImg(kind){if(!canvas.current)return;setExporting(true);const old=selectedId;setSelectedId(null);await new Promise(r=>setTimeout(r,60));try{const data=kind==='jpg'?await toJpeg(canvas.current,{quality:.94,pixelRatio:2,backgroundColor:bg}):await toPng(canvas.current,{pixelRatio:2,backgroundColor:bg});const a=document.createElement('a');a.href=data;a.download=`collage-${Date.now()}.${kind}`;a.click()}catch{alert('Экспорт не удался. Проверь внешние изображения.')}setSelectedId(old);setExporting(false)}

 return <main className="shell">
  <aside className="panel left"><div className="brand">1337tools <small>3.2</small></div>
   <div className="toolGrid"><button className={tool==='select'?'active':''} onClick={()=>setTool('select')}>↖ Select</button><button className={tool==='stamp'?'active':''} onClick={()=>setTool('stamp')}>✣ Stamp</button><button onClick={()=>fileRef.current?.click()}>+ Image</button><button onClick={()=>addText()}>+ Text</button></div>
   <input ref={fileRef} hidden type="file" accept="image/*" multiple onChange={e=>{addFiles(e.target.files);e.target.value=''}}/>
   <section><Title>Shapes</Title><div className="shapeButtons">{shapes.map(s=><button key={s} onClick={()=>addShape(s)}>{s}</button>)}</div></section>
   {tool==='stamp'&&<section><Title>Stamp / Brush</Title><label>Source<select value={stamp.type} onChange={e=>setStamp({...stamp,type:e.target.value})}><option value="text">Text</option>{shapes.map(s=><option key={s}>{s}</option>)}</select></label>{stamp.type==='text'&&<label>Word<input value={stamp.text} onChange={e=>setStamp({...stamp,text:e.target.value})}/></label>}<Range label="Size" min="8" max="80" value={stamp.size} onChange={v=>setStamp({...stamp,size:+v})}/><Range label="Spacing" min="3" max="80" value={stamp.spacing} onChange={v=>setStamp({...stamp,spacing:+v})}/><Range label="Rotation jitter" min="0" max="180" value={stamp.rotationJitter} onChange={v=>setStamp({...stamp,rotationJitter:+v})}/><Range label="Scale jitter" min="0" max="100" value={stamp.scaleJitter} onChange={v=>setStamp({...stamp,scaleJitter:+v})}/><Range label="Opacity jitter" min="0" max="95" value={stamp.opacityJitter} onChange={v=>setStamp({...stamp,opacityJitter:+v})}/><Range label="Order ↔ Chaos" min="0" max="100" value={stamp.chaos} onChange={v=>setStamp({...stamp,chaos:+v})}/><label className="check"><input type="checkbox" checked={stamp.follow} onChange={e=>setStamp({...stamp,follow:e.target.checked})}/> Follow direction</label><div className="note">Click = stamp. Hold + drag = brush. One stroke = one Undo.</div></section>}
   <section><Title>Canvas</Title><label>Ratio<select value={ratio} onChange={e=>setRatio(e.target.value)}><option value="1 / 1">1:1</option><option value="4 / 5">4:5</option><option value="9 / 16">9:16</option><option value="16 / 9">16:9</option><option value="3 / 2">3:2</option></select></label><label>Background<input type="color" value={bg} onChange={e=>setBg(e.target.value)}/></label></section>
   <section><Title>System</Title><div className="two"><button onClick={undo} disabled={!history.length}>Undo</button><button onClick={redo} disabled={!future.length}>Redo</button></div><button className="wide" onClick={variation}>Generate variation</button><button className="wide danger" onClick={clearCanvas}>Erase / Clear canvas</button><div className="two"><button disabled={exporting} onClick={()=>exportImg('png')}>PNG</button><button disabled={exporting} onClick={()=>exportImg('jpg')}>JPEG</button></div></section>
  </aside>

  <section className="workspace"><header className="topbar"><span>{layers.length} layers</span><b>IMAGE + TYPE + SHAPE → REPEAT → DISTRESS → RANDOMIZE</b></header><div className={`stage ${dragOver?'dragging':''}`} onDragOver={e=>{e.preventDefault();setDragOver(true)}} onDragLeave={()=>setDragOver(false)} onDrop={e=>{e.preventDefault();setDragOver(false);addFiles(e.dataTransfer.files)}}><div ref={canvas} className={`canvas ${tool==='stamp'?'stampCursor':''}`} style={{aspectRatio:ratio,background:bg}} onClick={canvasClick} onPointerDown={brushDown} onPointerMove={move} onPointerUp={up} onPointerLeave={up} onPointerCancel={up}>{!layers.length&&<div className="empty"><strong>DROP / STAMP / TYPE</strong><span>Build a composition, not a template.</span></div>}{[...layers].sort((a,b)=>a.z-b.z).map(l=>!l.hidden&&<Layer key={l.id} l={l} selected={l.id===selectedId} onDown={e=>onLayerDown(e,l)} onHandle={(e,h)=>onHandle(e,l,h)}/>)}</div></div></section>

  <aside className="panel right"><Title>Layers</Title><div className="layersList">{[...layers].sort((a,b)=>b.z-a.z).map(l=><div key={l.id} className={`layerRow ${l.id===selectedId?'active':''}`} onClick={()=>setSelectedId(l.id)}><span>{l.type==='image'?'IMG':l.type==='text'?'TXT':'SHP'}</span><b>{l.name||l.text||l.shape}</b><button onClick={e=>{e.stopPropagation();patch(l.id,{hidden:!l.hidden})}}>{l.hidden?'○':'●'}</button><button onClick={e=>{e.stopPropagation();patch(l.id,{locked:!l.locked})}}>{l.locked?'⌑':'⌁'}</button><button onClick={e=>{e.stopPropagation();reorder(l.id,1)}}>↑</button><button onClick={e=>{e.stopPropagation();reorder(l.id,-1)}}>↓</button></div>)}</div>
   {!selected?<div className="muted">Выбери объект. Клик по пустому месту снимает выделение.</div>:<>
    <section><Title>{selected.type} / Transform</Title><Range label="Width" min="2" max="120" value={Math.round(selected.width)} onChange={v=>patch(selected.id,{width:+v})}/><Range label="Height" min="2" max="120" value={Math.round(selected.height)} onChange={v=>patch(selected.id,{height:+v})}/><Range label="Rotate" min="-180" max="180" value={Math.round(selected.rotation)} onChange={v=>patch(selected.id,{rotation:+v})}/><Range label="Opacity" min="5" max="100" value={Math.round(selected.opacity*100)} onChange={v=>patch(selected.id,{opacity:+v/100})}/><label>Blend<select value={selected.blend} onChange={e=>patch(selected.id,{blend:e.target.value})}>{blends.map(b=><option key={b}>{b}</option>)}</select></label></section>
    {selected.type==='text'&&<section><Title>Type Lab</Title><textarea value={selected.text} onChange={e=>patch(selected.id,{text:e.target.value})}/><label>Font<select value={selected.fontFamily} onChange={e=>patch(selected.id,{fontFamily:e.target.value})}>{fonts.map(([v,n])=><option value={v} key={n}>{n}</option>)}</select></label><Range label="Size" min="10" max="180" value={selected.fontSize} onChange={v=>patch(selected.id,{fontSize:+v})}/><Range label="Weight" min="100" max="900" step="100" value={selected.fontWeight} onChange={v=>patch(selected.id,{fontWeight:+v})}/><Range label="Tracking" min="-10" max="30" value={selected.tracking} onChange={v=>patch(selected.id,{tracking:+v})}/><Range label="Line height" min="50" max="180" value={Math.round(selected.lineHeight*100)} onChange={v=>patch(selected.id,{lineHeight:+v/100})}/><Range label="Stretch X" min="30" max="250" value={Math.round(selected.scaleX*100)} onChange={v=>patch(selected.id,{scaleX:+v/100})}/><Range label="Stretch Y" min="30" max="250" value={Math.round(selected.scaleY*100)} onChange={v=>patch(selected.id,{scaleY:+v/100})}/><Range label="Outline" min="0" max="16" value={selected.outline} onChange={v=>patch(selected.id,{outline:+v})}/><label>Outline position<select value={selected.outlineMode||'center'} onChange={e=>patch(selected.id,{outlineMode:e.target.value})}><option value="inside">Inside</option><option value="center">Center</option><option value="outside">Outside</option></select></label><div className="two"><label>Color<input type="color" value={selected.color} onChange={e=>patch(selected.id,{color:e.target.value})}/></label><label>Outline<input type="color" value={selected.outlineColor} onChange={e=>patch(selected.id,{outlineColor:e.target.value})}/></label></div></section>}
    {selected.type==='shape'&&<section><Title>Shape</Title><div className="two"><label>Fill<input type="color" value={selected.fill} onChange={e=>patch(selected.id,{fill:e.target.value})}/></label><label>Stroke<input type="color" value={selected.stroke} onChange={e=>patch(selected.id,{stroke:e.target.value})}/></label></div><Range label="Stroke" min="0" max="20" value={selected.strokeWidth} onChange={v=>patch(selected.id,{strokeWidth:+v})}/></section>}
    {selected.type==='image'&&<ImageLab s={selected} patch={patch} patchFx={patchFx}/>} 
    <section><Title>Repeat / Pattern</Title><Range label="Count" min="1" max="40" value={repeat.count} onChange={v=>setRepeat({...repeat,count:+v})}/><Range label="Spacing" min="-20" max="20" value={repeat.spacing} onChange={v=>setRepeat({...repeat,spacing:+v})}/><Range label="Angle step" min="-45" max="45" value={repeat.angle} onChange={v=>setRepeat({...repeat,angle:+v})}/><Range label="Scale drift" min="-80" max="150" value={repeat.scale} onChange={v=>setRepeat({...repeat,scale:+v})}/><Range label="Opacity drift" min="0" max="95" value={repeat.opacity} onChange={v=>setRepeat({...repeat,opacity:+v})}/><Range label="Order ↔ Chaos" min="0" max="100" value={repeat.chaos} onChange={v=>setRepeat({...repeat,chaos:+v})}/><button className="wide primary" onClick={repeatSelected}>Repeat selected</button></section>
    <section className="actions"><button onClick={front}>Front</button><button onClick={back}>Back</button><button onClick={duplicate}>Duplicate</button><button className="danger" onClick={remove}>Delete</button></section>
   </>}
  </aside>
 </main>
}

function ImageLab({s,patch,patchFx}){const f={...fx0,...s.fx};return <section><Title>Image Lab</Title><label>Fit<select value={s.fit} onChange={e=>patch(s.id,{fit:e.target.value})}><option>cover</option><option>contain</option><option>fill</option></select></label><Range label="Corner radius" min="0" max="50" value={s.radius} onChange={v=>patch(s.id,{radius:+v})}/><h4>ADJUST</h4><Range label="Exposure" min="-50" max="50" value={f.exposure} onChange={v=>patchFx(s.id,'exposure',+v)}/><Range label="Contrast" min="0" max="300" value={f.contrast} onChange={v=>patchFx(s.id,'contrast',+v)}/><Range label="Saturation" min="0" max="250" value={f.saturation} onChange={v=>patchFx(s.id,'saturation',+v)}/><Range label="Grayscale" min="0" max="100" value={f.grayscale} onChange={v=>patchFx(s.id,'grayscale',+v)}/><Range label="Blur" min="0" max="16" value={f.blur} onChange={v=>patchFx(s.id,'blur',+v)}/><h4>DISTRESS</h4>{['threshold','grain','noise','scratches','halftone','xerox','fade'].map(k=><Range key={k} label={k} min="0" max="100" value={f[k]} onChange={v=>patchFx(s.id,k,+v)}/>)}</section>}
function Layer({l,selected,onDown,onHandle}){const style={left:`${l.x}%`,top:`${l.y}%`,width:`${l.width}%`,height:`${l.height}%`,opacity:l.opacity,zIndex:l.z,mixBlendMode:l.blend,transform:`translate(-50%,-50%) rotate(${l.rotation}deg)`};return <div className={`layer ${l.type}Layer ${selected?'selected':''} ${l.locked?'locked':''}`} style={style} onPointerDown={onDown}>{l.type==='image'&&<Img l={l}/>} {l.type==='text'&&<TextLayer l={l}/>} {l.type==='shape'&&<Shape l={l}/>} {selected&&!l.locked&&<Handles onHandle={onHandle}/>}</div>}
function Handles({onHandle}){return <>{['nw','ne','sw','se'].map(h=><i key={h} className={`handle ${h}`} onPointerDown={e=>onHandle(e,h)}/>)}<i className="rotateStem"/><i className="handle rotate" onPointerDown={e=>onHandle(e,'rotate')}/></>}
function Img({l}){const f={...fx0,...l.fx},th=f.threshold/100,filter=`brightness(${1+f.exposure/100}) contrast(${f.contrast/100+th*5+f.xerox/80}) saturate(${f.saturation/100}) grayscale(${Math.max(f.grayscale/100,th,f.xerox/120)}) blur(${f.blur}px)`;return <div className="imageFrame" style={{borderRadius:`${l.radius}%`}}><img src={l.src} alt={l.name||''} draggable={false} style={{objectFit:l.fit,filter}}/>{f.grain>0&&<i className="fx grain" style={{opacity:f.grain/150}}/>}{f.noise>0&&<i className="fx noise" style={{opacity:f.noise/130}}/>}{f.scratches>0&&<i className="fx scratches" style={{opacity:f.scratches/125}}/>}{f.halftone>0&&<i className="fx halftone" style={{opacity:f.halftone/115}}/>}{f.xerox>0&&<i className="fx xerox" style={{opacity:f.xerox/120}}/>}{f.fade>0&&<i className="fx fade" style={{opacity:f.fade/180}}/>}</div>}
function Shape({l}){if(l.shape==='triangle')return <div className="shape triangle" style={{'--fill':l.fill}}/>;if(l.shape==='star')return <div className="shape glyph" style={{color:l.fill}}>★</div>;if(l.shape==='cross')return <div className="shape cross" style={{'--fill':l.fill}}><i/><b/></div>;if(l.shape==='line')return <div className="shape line" style={{background:l.fill,height:Math.max(3,l.strokeWidth)}}/>;return <div className={`shape ${l.shape}`} style={{background:l.fill,border:`${l.strokeWidth}px solid ${l.stroke}`}}/>}
function TextLayer({l}){const base={fontFamily:l.fontFamily,fontSize:`${l.fontSize}px`,fontWeight:l.fontWeight,letterSpacing:`${l.tracking}px`,lineHeight:l.lineHeight,transform:`scale(${l.scaleX},${l.scaleY})`},mode=l.outlineMode||'center';if(mode==='outside')return <div className="textStack"><div className="textInner outlineBack" style={{...base,color:l.outlineColor,WebkitTextStroke:`${Math.max(0,l.outline*2)}px ${l.outlineColor}`}}>{l.text}</div><div className="textInner fillFront" style={{...base,color:l.color}}>{l.text}</div></div>;if(mode==='inside')return <div className="textInner" style={{...base,color:l.color,WebkitTextStroke:`${l.outline}px ${l.outlineColor}`,paintOrder:'fill stroke'}}>{l.text}</div>;return <div className="textInner" style={{...base,color:l.color,WebkitTextStroke:`${l.outline}px ${l.outlineColor}`}}>{l.text}</div>}
function Title({children}){return <div className="title">{children}</div>} function Range({label,value,onChange,...rest}){const min=rest.min??0,max=rest.max??100,step=rest.step??1;return <label className="range"><span>{label}</span><div className="rangeRow"><input type="range" value={value} onChange={e=>onChange(e.target.value)} {...rest}/><input className="numberInput" type="number" value={value} min={min} max={max} step={step} onChange={e=>{if(e.target.value!=='')onChange(clamp(+e.target.value,+min,+max))}} onDoubleClick={()=>onChange(label==='Rotate'?0:value)}/></div></label>}
function imgSize(src){return new Promise((res,rej)=>{const i=new Image();i.onload=()=>res({width:i.naturalWidth||1,height:i.naturalHeight||1});i.onerror=rej;i.src=src})}
