'use client';

import {useEffect,useMemo,useRef,useState} from 'react';
import {toPng,toJpeg} from 'html-to-image';

const uid=()=>globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random()}`;
const clamp=(n,a,b)=>Math.min(b,Math.max(a,n));
const blends=['normal','multiply','screen','overlay','darken','lighten','color-dodge','color-burn','hard-light','soft-light','difference','exclusion'];
const shapes=['rect','circle','triangle','star','cross','line'];
const fonts=[
  ['Arial, sans-serif','Arial'],['Inter, sans-serif','Inter'],['Oswald, sans-serif','Oswald'],['PT Sans, sans-serif','PT Sans'],['PT Serif, serif','PT Serif'],['Russo One, sans-serif','Russo One'],['Caveat, cursive','Caveat'],['Marck Script, cursive','Marck Script'],['Bad Script, cursive','Bad Script'],['Neucha, cursive','Neucha']
];
const fx0={exposure:0,contrast:100,saturation:100,grayscale:0,blur:0,threshold:0,grain:0,noise:0,scratches:0,halftone:0,xerox:0,fade:0};
const snap=(layers,selectedIds,primaryId)=>JSON.stringify({layers,selectedIds,primaryId});
const randSigned=()=>Math.random()*2-1;

export default function CollageEditor(){
 const [layers,setLayers]=useState([]),[selectedIds,setSelectedIds]=useState([]),[primaryId,setPrimaryId]=useState(null),[ratio,setRatio]=useState('4 / 5'),[bg,setBg]=useState('#f0ede4');
 const [tool,setTool]=useState('select'),[history,setHistory]=useState([]),[future,setFuture]=useState([]),[dragOver,setDragOver]=useState(false),[exporting,setExporting]=useState(false),[removingBg,setRemovingBg]=useState(false);
 const [repeat,setRepeat]=useState({count:8,spacing:7,angle:0,scale:0,opacity:0,chaos:10});
 const [stamp,setStamp]=useState({type:'text',text:'VOID',size:22,spacing:18,chaos:10,rotationJitter:20,scaleJitter:0,opacityJitter:0,follow:false});
 const canvas=useRef(null),fileRef=useRef(null),gesture=useRef(null),before=useRef(null),brush=useRef(null),variationBase=useRef(null);
 const [marquee,setMarquee]=useState(null);
 const selected=useMemo(()=>layers.find(l=>l.id===primaryId)||null,[layers,primaryId]);
 const selectedLayers=useMemo(()=>layers.filter(l=>selectedIds.includes(l.id)),[layers,selectedIds]);
 const multiBounds=useMemo(()=>getBounds(selectedLayers),[selectedLayers]);
 const currentSnap=()=>snap(layers,selectedIds,primaryId);
 const restore=s=>{setLayers(s.layers||[]);setSelectedIds(s.selectedIds||[]);setPrimaryId(s.primaryId||null)};
 const commit=(next,nextSelection=selectedIds,nextPrimary=primaryId)=>{setHistory(h=>[...h.slice(-39),currentSnap()]);setFuture([]);setLayers(next);setSelectedIds(nextSelection);setPrimaryId(nextPrimary)};
 const patch=(id,p)=>setLayers(ls=>ls.map(l=>l.id===id?{...l,...p}:l));
 const patchFx=(id,k,v)=>setLayers(ls=>ls.map(l=>l.id===id?{...l,fx:{...fx0,...l.fx,[k]:v}}:l));
 const undo=()=>{if(!history.length)return;const p=JSON.parse(history.at(-1));setFuture(f=>[currentSnap(),...f].slice(0,40));setHistory(h=>h.slice(0,-1));restore(p)};
 const redo=()=>{if(!future.length)return;const n=JSON.parse(future[0]);setHistory(h=>[...h,currentSnap()].slice(-40));setFuture(f=>f.slice(1));restore(n)};
 const setSelection=(ids,primary=ids.at(-1)||null)=>{setSelectedIds(ids);setPrimaryId(primary)};
 const selectAll=()=>{const ids=layers.filter(l=>!l.hidden).map(l=>l.id);setSelection(ids,ids.at(-1)||null)};

 useEffect(()=>{const fn=e=>{const meta=e.metaKey||e.ctrlKey;if(meta&&e.key.toLowerCase()==='a'&&!['INPUT','TEXTAREA'].includes(document.activeElement?.tagName)){e.preventDefault();selectAll()}if(meta&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo()}if(meta&&e.key.toLowerCase()==='d'){e.preventDefault();duplicate()}if((e.key==='Delete'||e.key==='Backspace')&&!['INPUT','TEXTAREA'].includes(document.activeElement?.tagName)){e.preventDefault();remove()}if(e.key==='Escape')setSelection([])};window.addEventListener('keydown',fn);return()=>window.removeEventListener('keydown',fn)});

 async function addFiles(list){
  const files=[...(list||[])].filter(f=>f.type.startsWith('image/')),adds=[];
  for(const f of files){const src=URL.createObjectURL(f);try{const d=await imgSize(src),ar=d.width/d.height;adds.push({id:uid(),type:'image',name:f.name,src,originalSrc:src,local:true,x:50,y:50,width:ar>=1?38:clamp(38*ar,16,38),height:ar>=1?clamp(38/ar,16,38):38,rotation:0,opacity:1,blend:'normal',hidden:false,locked:false,z:Date.now()+adds.length,fit:'cover',radius:0,fx:{...fx0}})}catch{URL.revokeObjectURL(src)}}
  if(adds.length){const ids=adds.map(a=>a.id);commit([...layers,...adds],ids,ids.at(-1))}
 }
 function addText(text='YOUR TEXT'){const l={id:uid(),type:'text',text,x:50,y:50,width:55,height:18,rotation:0,opacity:1,blend:'normal',hidden:false,locked:false,z:Date.now(),color:'#111111',fontFamily:fonts[0][0],fontSize:64,fontWeight:800,tracking:-2,lineHeight:.9,scaleX:1,scaleY:1,outline:0,outlineColor:'#111111',outlineMode:'center'};commit([...layers,l],[l.id],l.id)}
 function addShape(shape='rect'){const l={id:uid(),type:'shape',shape,x:50,y:50,width:shape==='line'?44:28,height:shape==='line'?6:28,rotation:0,opacity:1,blend:'normal',hidden:false,locked:false,z:Date.now(),fill:'#111111',stroke:'#111111',strokeWidth:0};commit([...layers,l],[l.id],l.id)}
 function remove(){if(!selectedIds.length)return;const removed=layers.filter(l=>selectedIds.includes(l.id));removed.forEach(l=>{if(l.local&&l.src&&l.src!==l.originalSrc)URL.revokeObjectURL(l.src)});commit(layers.filter(l=>!selectedIds.includes(l.id)),[],null)}
 function duplicate(){if(!selectedIds.length)return;const chosen=layers.filter(l=>selectedIds.includes(l.id)),base=Date.now(),copies=chosen.map((l,i)=>({...l,id:uid(),x:clamp(l.x+4,0,100),y:clamp(l.y+4,0,100),z:base+i})),ids=copies.map(c=>c.id);commit([...layers,...copies],ids,ids.at(-1))}
 function front(){if(!selectedIds.length)return;let z=Math.max(0,...layers.map(l=>l.z))+1;commit(layers.map(l=>selectedIds.includes(l.id)?{...l,z:z++}:l),selectedIds,primaryId)}
 function back(){if(!selectedIds.length)return;let z=Math.min(0,...layers.map(l=>l.z))-selectedIds.length;commit(layers.map(l=>selectedIds.includes(l.id)?{...l,z:z++}:l),selectedIds,primaryId)}
 function repeatSelected(){if(!selected)return;const copies=[],c=Math.pow(repeat.chaos/100,.72);for(let i=1;i<=repeat.count;i++){const t=i/repeat.count,scatter=2+20*c*c,scaleChaos=1+randSigned()*.65*c*c;copies.push({...selected,id:uid(),x:clamp(selected.x+i*repeat.spacing/2+randSigned()*scatter,0,100),y:clamp(selected.y+randSigned()*scatter,0,100),rotation:selected.rotation+i*repeat.angle+randSigned()*170*c*c,width:clamp(selected.width*(1+repeat.scale*t/100)*scaleChaos,2,120),height:clamp(selected.height*(1+repeat.scale*t/100)*scaleChaos,2,120),opacity:clamp((selected.opacity-repeat.opacity*t/100)*(1-Math.random()*.6*c*c),.05,1),z:Date.now()+i})}const ids=copies.map(c=>c.id);commit([...layers,...copies],ids,ids.at(-1)||primaryId)}
 function variation(){if(!layers.length)return;
  if(!variationBase.current)variationBase.current=JSON.parse(JSON.stringify(layers));
  const base=variationBase.current,intensity=1;
  const next=base.map((l,i)=>{const pos=22*intensity,rot=80*intensity,scale=Math.exp(randSigned()*.45*intensity);return {...l,x:clamp(l.x+randSigned()*pos, -20,120),y:clamp(l.y+randSigned()*pos,-20,120),rotation:l.rotation+randSigned()*rot,width:clamp(l.width*scale,2,160),height:clamp(l.height*scale,2,160),z:l.z+(Math.random()-.5)*1000}});
  commit(next,selectedIds,primaryId)
 }
 function clearCanvas(){if(!layers.length)return;if(!confirm('Erase ALL layers? Ctrl/Cmd+Z restores them. Canvas settings stay.'))return;commit([],[],null)}

 function makeStamp(x,y,angle=0){
  const c=Math.pow(stamp.chaos/100,.68),strong=c*c;
  const pos=1.5+13*strong,rotRange=stamp.rotationJitter*c+155*strong,scaleRange=(stamp.scaleJitter/100)*c+.72*strong,opacityRange=(stamp.opacityJitter/100)*c+.52*strong;
  const px=clamp(x+randSigned()*pos,0,100),py=clamp(y+randSigned()*pos,0,100),rot=angle+randSigned()*rotRange,scale=clamp(1+randSigned()*scaleRange,.18,2.4),opacity=clamp(1-Math.random()*opacityRange,.08,1);
  if(stamp.type==='text')return {id:uid(),type:'text',text:stamp.text||'STAMP',x:px,y:py,width:clamp(stamp.size*scale,2,120),height:10*scale,rotation:rot,opacity,blend:'multiply',hidden:false,locked:false,z:Date.now()+Math.random(),color:'#111',fontFamily:'Oswald, sans-serif',fontSize:58,fontWeight:700,tracking:0,lineHeight:.9,scaleX:1,scaleY:1,outline:0,outlineColor:'#111',outlineMode:'center'};
  return {id:uid(),type:'shape',shape:stamp.type,x:px,y:py,width:clamp(stamp.size/2*scale,2,120),height:clamp(stamp.size/2*scale,2,120),rotation:rot,opacity,blend:'multiply',hidden:false,locked:false,z:Date.now()+Math.random(),fill:'#111',stroke:'#111',strokeWidth:0}
 }
 function brushDown(e){
  if(tool==='select'&&e.target===canvas.current){e.preventDefault();const r=canvas.current.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*100,y=(e.clientY-r.top)/r.height*100;gesture.current={kind:'marquee',r,sx:x,sy:y,add:e.shiftKey,remove:e.altKey};setMarquee({x,y,w:0,h:0});canvas.current.setPointerCapture?.(e.pointerId);return}
  if(tool!=='stamp')return;e.preventDefault();e.stopPropagation();const r=canvas.current.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*100,y=(e.clientY-r.top)/r.height*100,l=makeStamp(x,y);before.current=currentSnap();brush.current={r,lastX:e.clientX,lastY:e.clientY,lastAngle:0,ids:[l.id]};setLayers(ls=>[...ls,l]);setSelection([l.id],l.id);canvas.current.setPointerCapture?.(e.pointerId)}

 function onLayerDown(e,l){
  if(tool==='stamp')return;e.stopPropagation();
  if(e.shiftKey){const ids=selectedIds.includes(l.id)?selectedIds.filter(id=>id!==l.id):[...selectedIds,l.id];setSelection(ids,ids.includes(l.id)?l.id:ids.at(-1));return}
  const ids=selectedIds.includes(l.id)?selectedIds:[l.id];setSelection(ids,l.id);if(l.locked)return;
  const r=canvas.current.getBoundingClientRect(),starts={};layers.filter(x=>ids.includes(x.id)&&!x.locked).forEach(x=>starts[x.id]={x:x.x,y:x.y});before.current=currentSnap();gesture.current={kind:'moveGroup',ids,sx:e.clientX,sy:e.clientY,starts,r};e.currentTarget.setPointerCapture?.(e.pointerId)
 }
 function onHandle(e,l,h){e.stopPropagation();e.preventDefault();const r=canvas.current.getBoundingClientRect(),cx=r.left+r.width*l.x/100,cy=r.top+r.height*l.y/100;before.current=currentSnap();gesture.current={kind:h==='rotate'?'rotate':'resize',h,id:l.id,sx:e.clientX,sy:e.clientY,w:l.width,hgt:l.height,r,cx,cy}}
 function onGroupHandle(e,h){
  if(!multiBounds)return;e.stopPropagation();e.preventDefault();const r=canvas.current.getBoundingClientRect(),cx=r.left+r.width*multiBounds.cx/100,cy=r.top+r.height*multiBounds.cy/100,starts={};selectedLayers.filter(l=>!l.locked).forEach(l=>starts[l.id]={x:l.x,y:l.y,width:l.width,height:l.height,rotation:l.rotation});before.current=currentSnap();gesture.current={kind:h==='rotate'?'groupRotate':'groupResize',h,sx:e.clientX,sy:e.clientY,r,cx,cy,b:{...multiBounds},starts,startAngle:Math.atan2(e.clientY-cy,e.clientX-cx)}
 }
 function move(e){
  const b=brush.current;
  if(b&&tool==='stamp'){const dx=e.clientX-b.lastX,dy=e.clientY-b.lastY,dist=Math.hypot(dx,dy);if(dist>=stamp.spacing){const angle=stamp.follow?Math.atan2(dy,dx)*180/Math.PI:0,steps=Math.max(1,Math.floor(dist/stamp.spacing)),adds=[];for(let i=1;i<=steps;i++){const px=b.lastX+dx*i/steps,py=b.lastY+dy*i/steps,x=(px-b.r.left)/b.r.width*100,y=(py-b.r.top)/b.r.height*100;adds.push(makeStamp(x,y,angle))}setLayers(ls=>[...ls,...adds]);b.ids.push(...adds.map(a=>a.id));b.lastX=e.clientX;b.lastY=e.clientY;b.lastAngle=angle}return}
  const g=gesture.current;if(!g)return;
  if(g.kind==='marquee'){const x=(e.clientX-g.r.left)/g.r.width*100,y=(e.clientY-g.r.top)/g.r.height*100;setMarquee({x:Math.min(g.sx,x),y:Math.min(g.sy,y),w:Math.abs(x-g.sx),h:Math.abs(y-g.sy)});return}
  if(g.kind==='moveGroup'){const dx=(e.clientX-g.sx)/g.r.width*100,dy=(e.clientY-g.sy)/g.r.height*100;setLayers(ls=>ls.map(l=>g.starts[l.id]?{...l,x:clamp(g.starts[l.id].x+dx,-20,120),y:clamp(g.starts[l.id].y+dy,-20,120)}:l));return}
  if(g.kind==='groupResize'){const dx=(e.clientX-g.sx)/g.r.width*100*(g.h.includes('w')?-2:2),dy=(e.clientY-g.sy)/g.r.height*100*(g.h.includes('n')?-2:2);let sx=clamp((g.b.width+dx)/Math.max(g.b.width,.1),.08,8),sy=clamp((g.b.height+dy)/Math.max(g.b.height,.1),.08,8);if(e.shiftKey){const s=Math.abs(dx)>Math.abs(dy)?sx:sy;sx=s;sy=s}setLayers(ls=>ls.map(l=>{const s=g.starts[l.id];if(!s)return l;return {...l,x:g.b.cx+(s.x-g.b.cx)*sx,y:g.b.cy+(s.y-g.b.cy)*sy,width:clamp(s.width*sx,1,200),height:clamp(s.height*sy,1,200)}}));return}
  if(g.kind==='groupRotate'){const a=Math.atan2(e.clientY-g.cy,e.clientX-g.cx),delta=(a-g.startAngle)*180/Math.PI,rad=delta*Math.PI/180;setLayers(ls=>ls.map(l=>{const s=g.starts[l.id];if(!s)return l;const dx=s.x-g.b.cx,dy=s.y-g.b.cy;return {...l,x:g.b.cx+dx*Math.cos(rad)-dy*Math.sin(rad),y:g.b.cy+dx*Math.sin(rad)+dy*Math.cos(rad),rotation:s.rotation+delta}}));return}
  const l=layers.find(x=>x.id===g.id);if(!l||l.locked)return;
  if(g.kind==='resize'){let w=clamp(g.w+(e.clientX-g.sx)/g.r.width*100*(g.h.includes('w')?-2:2),2,120),h=clamp(g.hgt+(e.clientY-g.sy)/g.r.height*100*(g.h.includes('n')?-2:2),2,120);if(e.shiftKey){const ar=g.w/g.hgt;if(Math.abs(e.clientX-g.sx)>Math.abs(e.clientY-g.sy))h=w/ar;else w=h*ar}patch(g.id,{width:w,height:h})}
  if(g.kind==='rotate')patch(g.id,{rotation:Math.atan2(e.clientY-g.cy,e.clientX-g.cx)*180/Math.PI+90})
 }
 function up(){if(brush.current){if(before.current){setHistory(h=>[...h.slice(-39),before.current]);setFuture([])}setSelection(brush.current.ids,brush.current.ids.at(-1));brush.current=null;before.current=null;return}if(!gesture.current)return;const g=gesture.current;if(g.kind==='marquee'){const m=marquee;if(m){const hits=layers.filter(l=>!l.hidden&&l.x+l.width/2>=m.x&&l.x-l.width/2<=m.x+m.w&&l.y+l.height/2>=m.y&&l.y-l.height/2<=m.y+m.h).map(l=>l.id);let ids=g.add?[...new Set([...selectedIds,...hits])]:g.remove?selectedIds.filter(id=>!hits.includes(id)):hits;setSelection(ids,ids.at(-1)||null)}setMarquee(null);gesture.current=null;return}if(before.current){setHistory(h=>[...h.slice(-39),before.current]);setFuture([])}gesture.current=null;before.current=null}
 function canvasClick(e){if(tool==='select'&&e.target===canvas.current&&!marquee&&!gesture.current)setSelection([])}
 function reorder(id,dir){const s=[...layers].sort((a,b)=>a.z-b.z),i=s.findIndex(l=>l.id===id),j=clamp(i+dir,0,s.length-1);if(i===j)return;[s[i],s[j]]=[s[j],s[i]];const base=Date.now();commit(s.map((l,k)=>({...l,z:base+k})),selectedIds,primaryId)}

 async function removeBackground(){
  if(!selected||selected.type!=='image'||removingBg)return;setRemovingBg(true);
  try{const blob=await simpleRemoveBackground(selected.src),url=URL.createObjectURL(blob),next=layers.map(l=>l.id===selected.id?{...l,src:url,originalSrc:l.originalSrc||l.src,bgRemoved:true}:l);commit(next,selectedIds,primaryId)}catch(err){console.error(err);alert('Remove BG failed for this image. Try a local image or a simpler background.')}finally{setRemovingBg(false)}
 }
 function restoreBackground(){if(!selected||selected.type!=='image'||!selected.originalSrc)return;const old=selected.src,next=layers.map(l=>l.id===selected.id?{...l,src:l.originalSrc,bgRemoved:false}:l);commit(next,selectedIds,primaryId);if(old!==selected.originalSrc&&old?.startsWith('blob:'))setTimeout(()=>URL.revokeObjectURL(old),500)}
 async function exportImg(kind){
  if(!canvas.current)return;setExporting(true);const oldIds=selectedIds,oldPrimary=primaryId;setSelection([]);await new Promise(r=>setTimeout(r,80));
  const imgs=[...canvas.current.querySelectorAll('img')],originals=imgs.map(i=>i.src);
  try{
   // Safari/html-to-image can fail on blob/object URLs. Inline every image before serialization.
   await Promise.all(imgs.map(async img=>{if(img.src.startsWith('data:'))return;img.src=await sourceToDataUrl(img.src);await waitImage(img)}));
   const opts={pixelRatio:2,backgroundColor:bg,cacheBust:true,skipFonts:true};
   const data=kind==='jpg'?await toJpeg(canvas.current,{...opts,quality:.94}):await toPng(canvas.current,opts);
   const a=document.createElement('a');a.href=data;a.download=`1337tools-${Date.now()}.${kind}`;document.body.appendChild(a);a.click();a.remove();
  }catch(err){console.error('1337tools export failed:',err);alert(`Экспорт не удался: ${err?.message||'неизвестная ошибка'}`)}
  finally{imgs.forEach((img,i)=>{if(originals[i])img.src=originals[i]});setSelection(oldIds,oldPrimary);setExporting(false)}
 }

 return <main className="shell">
  <aside className="panel left"><div className="brand">1337tools <small>3.4.2</small></div>
   <div className="toolGrid"><button className={tool==='select'?'active':''} onClick={()=>setTool('select')}>↖ Select</button><button className={tool==='stamp'?'active':''} onClick={()=>setTool('stamp')}>✣ Stamp</button><button onClick={()=>fileRef.current?.click()}>+ Image</button><button onClick={()=>addText()}>+ Text</button></div>
   <input ref={fileRef} hidden type="file" accept="image/*" multiple onChange={e=>{addFiles(e.target.files);e.target.value=''}}/>
   <section><Title>Shapes</Title><div className="shapeButtons">{shapes.map(s=><button key={s} onClick={()=>addShape(s)}>{s}</button>)}</div></section>
   {tool==='stamp'&&<section><Title>Stamp / Brush</Title><label>Source<select value={stamp.type} onChange={e=>setStamp({...stamp,type:e.target.value})}><option value="text">Text</option>{shapes.map(s=><option key={s}>{s}</option>)}</select></label>{stamp.type==='text'&&<label>Word<input value={stamp.text} onChange={e=>setStamp({...stamp,text:e.target.value})}/></label>}<Range label="Size" min="8" max="80" value={stamp.size} onChange={v=>setStamp({...stamp,size:+v})}/><Range label="Spacing" min="3" max="80" value={stamp.spacing} onChange={v=>setStamp({...stamp,spacing:+v})}/><Range label="Rotation jitter" min="0" max="180" value={stamp.rotationJitter} onChange={v=>setStamp({...stamp,rotationJitter:+v})}/><Range label="Scale jitter" min="0" max="100" value={stamp.scaleJitter} onChange={v=>setStamp({...stamp,scaleJitter:+v})}/><Range label="Opacity jitter" min="0" max="95" value={stamp.opacityJitter} onChange={v=>setStamp({...stamp,opacityJitter:+v})}/><Range label="Order ↔ Chaos" min="0" max="100" value={stamp.chaos} onChange={v=>setStamp({...stamp,chaos:+v})}/><label className="check"><input type="checkbox" checked={stamp.follow} onChange={e=>setStamp({...stamp,follow:e.target.checked})}/> Follow direction</label><div className="note">Chaos now affects position + rotation + scale + opacity. Hold + drag = one Undo.</div></section>}
   <section><Title>Canvas</Title><label>Ratio<select value={ratio} onChange={e=>setRatio(e.target.value)}><option value="1 / 1">1:1</option><option value="4 / 5">4:5</option><option value="9 / 16">9:16</option><option value="16 / 9">16:9</option><option value="3 / 2">3:2</option></select></label><label>Background<input type="color" value={bg} onChange={e=>setBg(e.target.value)}/></label></section>
   <section><Title>System</Title><div className="two"><button onClick={undo} disabled={!history.length}>Undo</button><button onClick={redo} disabled={!future.length}>Redo</button></div><button className="wide" onClick={selectAll} disabled={!layers.length}>Select all · ⌘/Ctrl+A</button><button className="wide" onClick={variation}>Generate variation</button><button className="wide danger eraseAll" onClick={clearCanvas}>ERASE ALL</button><div className="two"><button disabled={exporting} onClick={()=>exportImg('png')}>PNG</button><button disabled={exporting} onClick={()=>exportImg('jpg')}>JPEG</button></div></section>
  </aside>

  <section className="workspace"><header className="topbar"><span>{layers.length} layers · {selectedIds.length} selected</span><b>IMAGE + TYPE + SHAPE → REPEAT → DISTRESS → RANDOMIZE</b></header><div className={`stage ${dragOver?'dragging':''}`} onDragOver={e=>{e.preventDefault();setDragOver(true)}} onDragLeave={()=>setDragOver(false)} onDrop={e=>{e.preventDefault();setDragOver(false);addFiles(e.dataTransfer.files)}}><div ref={canvas} className={`canvas ${tool==='stamp'?'stampCursor':''}`} style={{aspectRatio:ratio,background:bg}} onClick={canvasClick} onPointerDown={brushDown} onPointerMove={move} onPointerUp={up} onPointerLeave={up} onPointerCancel={up}>{!layers.length&&<div className="empty"><strong>DROP / STAMP / TYPE</strong><span>Build a composition, not a template.</span></div>}{[...layers].sort((a,b)=>a.z-b.z).map(l=>!l.hidden&&<Layer key={l.id} l={l} selected={selectedIds.includes(l.id)} primary={l.id===primaryId} multi={selectedIds.length>1} onDown={e=>onLayerDown(e,l)} onHandle={(e,h)=>onHandle(e,l,h)}/>)}{selectedIds.length>1&&multiBounds&&<MultiBox bounds={multiBounds} onHandle={onGroupHandle}/>} {marquee&&<div className="marquee" style={{left:`${marquee.x}%`,top:`${marquee.y}%`,width:`${marquee.w}%`,height:`${marquee.h}%`}}/>}</div></div></section>

  <aside className="panel right"><Title>Layers</Title><div className="layersList">{[...layers].sort((a,b)=>b.z-a.z).map(l=><div key={l.id} className={`layerRow ${selectedIds.includes(l.id)?'active':''}`} onClick={e=>{if(e.shiftKey){const ids=selectedIds.includes(l.id)?selectedIds.filter(id=>id!==l.id):[...selectedIds,l.id];setSelection(ids,ids.includes(l.id)?l.id:ids.at(-1))}else setSelection([l.id],l.id)}}><span>{l.type==='image'?'IMG':l.type==='text'?'TXT':'SHP'}</span><b>{l.name||l.text||l.shape}</b><button onClick={e=>{e.stopPropagation();patch(l.id,{hidden:!l.hidden})}}>{l.hidden?'○':'●'}</button><button onClick={e=>{e.stopPropagation();patch(l.id,{locked:!l.locked})}}>{l.locked?'⌑':'⌁'}</button><button onClick={e=>{e.stopPropagation();reorder(l.id,1)}}>↑</button><button onClick={e=>{e.stopPropagation();reorder(l.id,-1)}}>↓</button></div>)}</div>
   {!selected?<div className="muted">Select an object. Shift-click adds/removes layers. Ctrl/Cmd+A selects all visible layers.</div>:<>
    {selectedIds.length>1?<><section><Title>Multi Selection</Title><div className="muted">{selectedIds.length} layers selected. Drag/resize/rotate as one temporary selection.</div><Range label="Opacity" min="5" max="100" value={Math.round(selected.opacity*100)} onChange={v=>setLayers(ls=>ls.map(l=>selectedIds.includes(l.id)?{...l,opacity:+v/100}:l))}/><label>Blend<select value={selected.blend} onChange={e=>setLayers(ls=>ls.map(l=>selectedIds.includes(l.id)?{...l,blend:e.target.value}:l))}>{blends.map(b=><option key={b}>{b}</option>)}</select></label></section><section><Title>Group Effects · images</Title><div className="muted">Effects apply to image layers inside the selection ({selectedLayers.filter(l=>l.type==='image').length}/{selectedIds.length}).</div>{['threshold','grain','noise','scratches','halftone','xerox','fade'].map(k=><Range key={k} label={k} min="0" max="100" value={Math.round(({...fx0,...selectedLayers.find(l=>l.type==='image')?.fx}[k])||0)} onChange={v=>setLayers(ls=>ls.map(l=>selectedIds.includes(l.id)&&l.type==='image'?{...l,fx:{...fx0,...l.fx,[k]:+v}}:l))}/>)}</section></>:<section><Title>{selected.type} / Transform</Title><Range label="Width" min="2" max="120" value={Math.round(selected.width)} onChange={v=>patch(selected.id,{width:+v})}/><Range label="Height" min="2" max="120" value={Math.round(selected.height)} onChange={v=>patch(selected.id,{height:+v})}/><Range label="Rotate" min="-180" max="180" value={Math.round(selected.rotation)} onChange={v=>patch(selected.id,{rotation:+v})}/><Range label="Opacity" min="5" max="100" value={Math.round(selected.opacity*100)} onChange={v=>patch(selected.id,{opacity:+v/100})}/><label>Blend<select value={selected.blend} onChange={e=>patch(selected.id,{blend:e.target.value})}>{blends.map(b=><option key={b}>{b}</option>)}</select></label></section>}
    {selectedIds.length===1&&selected.type==='text'&&<section><Title>Type Lab</Title><textarea value={selected.text} onChange={e=>patch(selected.id,{text:e.target.value})}/><label>Font<select value={selected.fontFamily} onChange={e=>patch(selected.id,{fontFamily:e.target.value})}>{fonts.map(([v,n])=><option value={v} key={n}>{n}</option>)}</select></label><Range label="Size" min="10" max="180" value={selected.fontSize} onChange={v=>patch(selected.id,{fontSize:+v})}/><Range label="Weight" min="100" max="900" step="100" value={selected.fontWeight} onChange={v=>patch(selected.id,{fontWeight:+v})}/><Range label="Tracking" min="-10" max="30" value={selected.tracking} onChange={v=>patch(selected.id,{tracking:+v})}/><Range label="Line height" min="50" max="180" value={Math.round(selected.lineHeight*100)} onChange={v=>patch(selected.id,{lineHeight:+v/100})}/><Range label="Stretch X" min="30" max="250" value={Math.round(selected.scaleX*100)} onChange={v=>patch(selected.id,{scaleX:+v/100})}/><Range label="Stretch Y" min="30" max="250" value={Math.round(selected.scaleY*100)} onChange={v=>patch(selected.id,{scaleY:+v/100})}/><Range label="Outline" min="0" max="16" value={selected.outline} onChange={v=>patch(selected.id,{outline:+v})}/><label>Outline position<select value={selected.outlineMode||'center'} onChange={e=>patch(selected.id,{outlineMode:e.target.value})}><option value="inside">Inside</option><option value="center">Center</option><option value="outside">Outside</option></select></label><div className="two"><label>Color<input type="color" value={selected.color} onChange={e=>patch(selected.id,{color:e.target.value})}/></label><label>Outline<input type="color" value={selected.outlineColor} onChange={e=>patch(selected.id,{outlineColor:e.target.value})}/></label></div></section>}
    {selectedIds.length===1&&selected.type==='shape'&&<section><Title>Shape</Title><div className="two"><label>Fill<input type="color" value={selected.fill} onChange={e=>patch(selected.id,{fill:e.target.value})}/></label><label>Stroke<input type="color" value={selected.stroke} onChange={e=>patch(selected.id,{stroke:e.target.value})}/></label></div><Range label="Stroke" min="0" max="20" value={selected.strokeWidth} onChange={v=>patch(selected.id,{strokeWidth:+v})}/></section>}
    {selectedIds.length===1&&selected.type==='image'&&<ImageLab s={selected} patch={patch} patchFx={patchFx} removingBg={removingBg} removeBackground={removeBackground} restoreBackground={restoreBackground}/>} 
    {selectedIds.length===1&&<section><Title>Repeat / Pattern</Title><Range label="Count" min="1" max="40" value={repeat.count} onChange={v=>setRepeat({...repeat,count:+v})}/><Range label="Spacing" min="-20" max="20" value={repeat.spacing} onChange={v=>setRepeat({...repeat,spacing:+v})}/><Range label="Angle step" min="-45" max="45" value={repeat.angle} onChange={v=>setRepeat({...repeat,angle:+v})}/><Range label="Scale drift" min="-80" max="150" value={repeat.scale} onChange={v=>setRepeat({...repeat,scale:+v})}/><Range label="Opacity drift" min="0" max="95" value={repeat.opacity} onChange={v=>setRepeat({...repeat,opacity:+v})}/><Range label="Order ↔ Chaos" min="0" max="100" value={repeat.chaos} onChange={v=>setRepeat({...repeat,chaos:+v})}/><button className="wide primary" onClick={repeatSelected}>Repeat selected</button></section>}
    <section className="actions"><button onClick={front}>Front</button><button onClick={back}>Back</button><button onClick={duplicate}>Duplicate</button><button className="danger" onClick={remove}>Delete</button></section>
   </>}
  </aside>
 </main>
}

function ImageLab({s,patch,patchFx,removingBg,removeBackground,restoreBackground}){const f={...fx0,...s.fx};return <section><Title>Image Lab</Title><label>Fit<select value={s.fit} onChange={e=>patch(s.id,{fit:e.target.value})}><option>cover</option><option>contain</option><option>fill</option></select></label><Range label="Corner radius" min="0" max="50" value={s.radius} onChange={v=>patch(s.id,{radius:+v})}/><div className="two"><button className="primary" disabled={removingBg} onClick={removeBackground}>{removingBg?'Removing…':'Remove BG β'}</button><button disabled={!s.originalSrc||!s.bgRemoved} onClick={restoreBackground}>Restore BG</button></div><div className="note">Alpha-safe effects: PNG transparency is preserved. Remove BG β works locally and is best on clear/flat backgrounds.</div><h4>ADJUST</h4><Range label="Exposure" min="-50" max="50" value={f.exposure} onChange={v=>patchFx(s.id,'exposure',+v)}/><Range label="Contrast" min="0" max="300" value={f.contrast} onChange={v=>patchFx(s.id,'contrast',+v)}/><Range label="Saturation" min="0" max="250" value={f.saturation} onChange={v=>patchFx(s.id,'saturation',+v)}/><Range label="Grayscale" min="0" max="100" value={f.grayscale} onChange={v=>patchFx(s.id,'grayscale',+v)}/><Range label="Blur" min="0" max="16" value={f.blur} onChange={v=>patchFx(s.id,'blur',+v)}/><h4>DISTRESS</h4>{['threshold','grain','noise','scratches','halftone','xerox','fade'].map(k=><Range key={k} label={k} min="0" max="100" value={f[k]} onChange={v=>patchFx(s.id,k,+v)}/>)}</section>}
function Layer({l,selected,primary,multi,onDown,onHandle}){const style={left:`${l.x}%`,top:`${l.y}%`,width:`${l.width}%`,height:`${l.height}%`,opacity:l.opacity,zIndex:l.z,mixBlendMode:l.blend,transform:`translate(-50%,-50%) rotate(${l.rotation}deg)`};return <div className={`layer ${l.type}Layer ${selected?'selected':''} ${primary?'primarySelected':''} ${l.locked?'locked':''}`} style={style} onPointerDown={onDown}>{l.type==='image'&&<Img l={l}/>} {l.type==='text'&&<TextLayer l={l}/>} {l.type==='shape'&&<Shape l={l}/>} {primary&&!multi&&!l.locked&&<Handles onHandle={onHandle}/>}</div>}
function MultiBox({bounds,onHandle}){const style={left:`${bounds.cx}%`,top:`${bounds.cy}%`,width:`${bounds.width}%`,height:`${bounds.height}%`};return <div className="multiBox" style={style}><Handles onHandle={onHandle}/></div>}
function Handles({onHandle}){return <>{['nw','ne','sw','se'].map(h=><i key={h} className={`handle ${h}`} onPointerDown={e=>onHandle(e,h)}/>)}<i className="rotateStem"/><i className="handle rotate" onPointerDown={e=>onHandle(e,'rotate')}/></>}
function Img({l}){const f={...fx0,...l.fx},th=f.threshold/100,filter=`brightness(${1+f.exposure/100}) contrast(${f.contrast/100+th*5+f.xerox/80}) saturate(${f.saturation/100}) grayscale(${Math.max(f.grayscale/100,th,f.xerox/120)}) blur(${f.blur}px)`,mask={WebkitMaskImage:`url("${l.src}")`,maskImage:`url("${l.src}")`,WebkitMaskRepeat:'no-repeat',maskRepeat:'no-repeat',WebkitMaskPosition:'center',maskPosition:'center',WebkitMaskSize:l.fit==='fill'?'100% 100%':l.fit==='contain'?'contain':'cover',maskSize:l.fit==='fill'?'100% 100%':l.fit==='contain'?'contain':'cover'};return <div className="imageFrame" style={{borderRadius:`${l.radius}%`}}><img src={l.src} alt={l.name||''} draggable={false} style={{objectFit:l.fit,filter}}/><div className="fxMask" style={mask}>{f.grain>0&&<i className="fx grain" style={{opacity:f.grain/150}}/>}{f.noise>0&&<i className="fx noise" style={{opacity:f.noise/130}}/>}{f.scratches>0&&<i className="fx scratches" style={{opacity:f.scratches/125}}/>}{f.halftone>0&&<i className="fx halftone" style={{opacity:f.halftone/115}}/>}{f.xerox>0&&<i className="fx xerox" style={{opacity:f.xerox/120}}/>}{f.fade>0&&<i className="fx fade" style={{opacity:f.fade/180}}/>}</div></div>}
function Shape({l}){if(l.shape==='triangle')return <div className="shape triangle" style={{'--fill':l.fill}}/>;if(l.shape==='star')return <svg className="shape starSvg" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true"><polygon points="50,2 61,36 97,36 68,57 79,92 50,71 21,92 32,57 3,36 39,36" fill={l.fill} stroke={l.stroke} strokeWidth={l.strokeWidth}/></svg>;if(l.shape==='cross')return <div className="shape cross" style={{'--fill':l.fill}}><i/><b/></div>;if(l.shape==='line')return <div className="shape line lineOuter" style={{background:l.stroke,height:`${3+l.strokeWidth*2}px`}}><i style={{background:l.fill,height:'3px'}}/></div>;return <div className={`shape ${l.shape}`} style={{background:l.fill,border:`${l.strokeWidth}px solid ${l.stroke}`}}/>}
function TextLayer({l}){const base={fontFamily:l.fontFamily,fontSize:`${l.fontSize}px`,fontWeight:l.fontWeight,letterSpacing:`${l.tracking}px`,lineHeight:l.lineHeight,transform:`scale(${l.scaleX},${l.scaleY})`},mode=l.outlineMode||'center';if(mode==='outside')return <div className="textStack"><div className="textInner outlineBack" style={{...base,color:l.outlineColor,WebkitTextStroke:`${Math.max(0,l.outline*2)}px ${l.outlineColor}`}}>{l.text}</div><div className="textInner fillFront" style={{...base,color:l.color}}>{l.text}</div></div>;if(mode==='inside')return <div className="textInner" style={{...base,color:l.color,WebkitTextStroke:`${l.outline}px ${l.outlineColor}`,paintOrder:'fill stroke'}}>{l.text}</div>;return <div className="textInner" style={{...base,color:l.color,WebkitTextStroke:`${l.outline}px ${l.outlineColor}`}}>{l.text}</div>}
function Title({children}){return <div className="title">{children}</div>}
function Range({label,value,onChange,...rest}){const min=rest.min??0,max=rest.max??100,step=rest.step??1;return <label className="range"><span>{label}</span><div className="rangeRow"><input type="range" value={value} onChange={e=>onChange(e.target.value)} {...rest}/><input className="numberInput" type="number" value={value} min={min} max={max} step={step} onChange={e=>{if(e.target.value!=='')onChange(clamp(+e.target.value,+min,+max))}} onDoubleClick={()=>onChange(label==='Rotate'?0:value)}/></div></label>}
function imgSize(src){return new Promise((res,rej)=>{const i=new Image();i.onload=()=>res({width:i.naturalWidth||1,height:i.naturalHeight||1});i.onerror=rej;i.src=src})}
function getBounds(items){if(!items.length)return null;let minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity;for(const l of items){minX=Math.min(minX,l.x-l.width/2);maxX=Math.max(maxX,l.x+l.width/2);minY=Math.min(minY,l.y-l.height/2);maxY=Math.max(maxY,l.y+l.height/2)}return {minX,minY,maxX,maxY,cx:(minX+maxX)/2,cy:(minY+maxY)/2,width:Math.max(.1,maxX-minX),height:Math.max(.1,maxY-minY)}}
async function simpleRemoveBackground(src){
 const img=await loadImage(src),max=1400,scale=Math.min(1,max/Math.max(img.naturalWidth,img.naturalHeight)),w=Math.max(1,Math.round(img.naturalWidth*scale)),h=Math.max(1,Math.round(img.naturalHeight*scale)),c=document.createElement('canvas');c.width=w;c.height=h;const ctx=c.getContext('2d',{willReadFrequently:true});ctx.drawImage(img,0,0,w,h);const im=ctx.getImageData(0,0,w,h),d=im.data,pts=[[2,2],[w-3,2],[2,h-3],[w-3,h-3],[Math.floor(w/2),2],[Math.floor(w/2),h-3]],bg=pts.reduce((a,[x,y])=>{const i=(y*w+x)*4;return [a[0]+d[i],a[1]+d[i+1],a[2]+d[i+2]]},[0,0,0]).map(v=>v/pts.length),tol=72,soft=38;
 for(let i=0;i<d.length;i+=4){const dist=Math.hypot(d[i]-bg[0],d[i+1]-bg[1],d[i+2]-bg[2]);if(dist<tol)d[i+3]=0;else if(dist<tol+soft)d[i+3]=Math.round(255*(dist-tol)/soft)}ctx.putImageData(im,0,0);return await new Promise((res,rej)=>c.toBlob(b=>b?res(b):rej(new Error('PNG encode failed')),'image/png'))
}
function loadImage(src){return new Promise((res,rej)=>{const i=new Image();i.crossOrigin='anonymous';i.onload=()=>res(i);i.onerror=rej;i.src=src})}

async function sourceToDataUrl(src){const r=await fetch(src);if(!r.ok)throw new Error(`image fetch ${r.status}`);const b=await r.blob();return await new Promise((res,rej)=>{const fr=new FileReader();fr.onload=()=>res(fr.result);fr.onerror=()=>rej(fr.error||new Error('FileReader failed'));fr.readAsDataURL(b)})}
function waitImage(img){return img.complete?Promise.resolve():new Promise((res,rej)=>{img.onload=()=>res();img.onerror=()=>rej(new Error('image decode failed'))})}
